#!/bin/sh
# 日本語ロケールが入っていること
# dpkg-reconfigure locales

# sources.list のパッケージに non-free contrib を追加
sed -i.orig -e '/^deb.*debian/{s/$/ non-free contrib/}' /etc/apt/sources.list

apt update
apt full-upgrade
apt autoremove
apt purge
apt -y install git locate tcsh vim screen sudo
apt -y remove nano

# edito sudoers のファイルを編集
# visudo

# - optional
apt -y install sharutils gcc make
apt -y install manpages manpages-dev manpages-ja manpages-ja-dev
apt -y install syslog-ng sysstat zip bind9-dnsutils sharutils
# bind9-dnsutils - dig, nslookup
# sharutils - shar, uuencode

# Fedora の場合の日本語ロケール追加
# dnf install glibc-langpack-ja

# インストール済みの一覧
# apt list --installed
# 設定ファイルごとアンインストール
# apt --purge remove <foo>

chsh -s /usr/bin/tcsh
git clone https://github.com/jp-yen/dotfiles.git
install dotfiles/csh.cshrc /etc/csh.cshrc
install dotfiles/screenrc /etc/screenrc
install dotfiles/vimrc /etc/vim/vimrc

VIM_COLORS=/usr/share/vim/vim90/colors
( cd $VIM_COLORS && wget -N https://raw.githubusercontent.com/michalbachowski/vim-wombat256mod/master/colors/wombat256mod.vim )
( cd $VIM_COLORS && wget -N https://raw.githubusercontent.com/romainl/Apprentice/master/colors/apprentice.vim )
( cd $VIM_COLORS && wget -N https://raw.githubusercontent.com/karoliskoncevicius/moonshine-vim/master/colors/moonshine.vim )
( cd $VIM_COLORS && wget -N https://raw.githubusercontent.com/Haron-Prime/Antares/master/colors/antares.vim )

exit

# CD インストール net-inst を使うと /etc/apt/sources.list が自動的に更新され便利
# (Cinnamon), SSH, 標準システムユーティリティ
#
# /etc/apt/sources.list の例
# deb cdrom:[Debian GNU/Linux 11.6.0 _Bullseye_ - Official amd64 NETINST 20221217-10:42]/ bullseye main
deb http://ftp.riken.jp/Linux/debian/debian/ bullseye main
deb-src http://ftp.riken.jp/Linux/debian/debian/ bullseye main

deb http://security.debian.org/debian-security bullseye-security main
deb-src http://security.debian.org/debian-security bullseye-security main

# bullseye-updates, to get updates before a point release is made;
# see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_updates_and_backports
deb http://ftp.riken.jp/Linux/debian/debian/ bullseye-updates main
deb-src http://ftp.riken.jp/Linux/debian/debian/ bullseye-updates main

# This system was installed using small removable media
# (e.g. netinst, live or single CD). The matching "deb cdrom"
# entries were disabled at the end of the installation process.
# For information about how to configure apt package sources,
# see the sources.list(5) manual.

deb http://deb.debian.org/debian/ bullseye main contrib non-free
deb http://deb.debian.org/debian/ bullseye-backports main contrib non-free
